/** Declaration file generated by dts-gen */

export function autoComplete(e: any, o: any): any;

export function interestByRegion(e: any, o: any): any;

export function interestOverTime(e: any, o: any): any;

export function relatedQueries(e: any, o: any): any;

export function relatedTopics(e: any, o: any): any;

export namespace autoComplete {
    const prototype: {
    };

}

export namespace interestByRegion {
    const prototype: {
    };

}

export namespace interestOverTime {
    const prototype: {
    };

}

export namespace relatedQueries {
    const prototype: {
    };

}

export namespace relatedTopics {
    const prototype: {
    };

}

